name: Bot (daily)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 22 * * *' # 日本時間 7時
  workflow_dispatch:

env:
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

jobs:
  ci:
    strategy:
      fail-fast: false

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.0
      - name: Installation
        run: poetry install
      - name: Test
        run: poetry run python -m unittest
        continue-on-error: true
      - name: Favorite
        run: poetry run python favorite.py
      - name: Tweet
        if: ${{ github.event_name == 'schedule' or github.event_name == 'workflow_dispatch' }}
        run: poetry run python main.py

      - name: Commit Files
        if: ${{ github.event_name == 'schedule' or github.event_name == 'workflow_dispatch' }}
        run: |
          bash update.sh
          git add -A
          git config user.name github-actions
          git config user.email github-actions@github.com
          now=`TZ=JST-9 date`
          git commit -m "${now}"
          git push

      - name: Notify Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}